version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: todoapp-postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d todoapp"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:


